var searchData=
[
  ['test_20agents',['Test Agents',['../df/d6b/md_parlai_agents_test_agents_README.html',1,'']]],
  ['tfidf_20retriever',['TFIDF Retriever',['../d9/dd2/md_parlai_agents_tfidf_retriever_README.html',1,'']]],
  ['transformer',['Transformer',['../db/da2/md_parlai_agents_transformer_README.html',1,'']]],
  ['terminal_20chat',['Terminal Chat',['../dd/d6d/md_parlai_chat_service_services_terminal_chat_README.html',1,'']]],
  ['task_3a_20aqua',['Task: AQuA',['../d0/d03/md_parlai_tasks_aqua_README.html',1,'']]],
  ['task_3a_20babi_201k',['Task: bAbI 1k',['../dc/dd2/md_parlai_tasks_babi_README.html',1,'']]],
  ['task_3a_20booktest',['Task: BookTest',['../d4/d5c/md_parlai_tasks_booktest_README.html',1,'']]],
  ['task_3a_20children_27s_20book_20test_20_28cbt_29',['Task: Children&apos;s Book Test (CBT)',['../de/da7/md_parlai_tasks_cbt_README.html',1,'']]],
  ['task_3a_20clevr',['Task: CLEVR',['../db/d89/md_parlai_tasks_clevr_README.html',1,'']]],
  ['task_3a_20cnn_2fdm_20summarisation',['Task: CNN/DM Summarisation',['../d3/d31/md_parlai_tasks_cnn_dm_README.html',1,'']]],
  ['task_3a_20coco_5fcaptions',['Task: COCO_Captions',['../de/d1e/md_parlai_tasks_coco_caption_README.html',1,'']]],
  ['task_3a_20convai2',['Task: ConvAI2',['../d3/db0/md_parlai_tasks_convai2_README.html',1,'']]],
  ['task_3a_20convai2_5fwild_5fevaluation',['Task: ConvAI2_wild_evaluation',['../d4/d13/md_parlai_tasks_convai2_wild_evaluation_README.html',1,'']]],
  ['task_3a_20convai_5fchitchat',['Task: ConvAI_ChitChat',['../d3/d27/md_parlai_tasks_convai_chitchat_README.html',1,'']]],
  ['task_3a_20choice_20of_20plausible_20alternatives',['Task: Choice of Plausible Alternatives',['../da/d30/md_parlai_tasks_copa_README.html',1,'']]],
  ['task_3a_20conversational_20question_20answering_20challenge',['Task: Conversational Question Answering Challenge',['../d1/d26/md_parlai_tasks_coqa_README.html',1,'']]],
  ['task_3a_20cornell_20movie',['Task: Cornell Movie',['../d7/d9f/md_parlai_tasks_cornell_movie_README.html',1,'']]],
  ['task_3a_20daily_20dialog',['Task: Daily Dialog',['../da/d20/md_parlai_tasks_dailydialog_README.html',1,'']]],
  ['task_3a_20dialog_20based_20language_20learning_3a_20babi_20task',['Task: Dialog Based Language Learning: bAbI Task',['../d3/df7/md_parlai_tasks_dbll_babi_README.html',1,'']]],
  ['task_3a_20dialog_20based_20language_20learning_3a_20wikimovies_20task',['Task: Dialog Based Language Learning: WikiMovies Task',['../d4/d79/md_parlai_tasks_dbll_movie_README.html',1,'']]],
  ['task_3a_20deal_20or_20no_20deal',['Task: Deal or No Deal',['../dd/d53/md_parlai_tasks_dealnodeal_README.html',1,'']]],
  ['task_3a_20decanlp_3a_20the_20natural_20language_20decathlon',['Task: DecaNLP: The Natural Language Decathlon',['../dd/d4e/md_parlai_tasks_decanlp_README.html',1,'']]],
  ['task_3a_20dialog_20babi_2b',['Task: Dialog bAbI+',['../d7/d56/md_parlai_tasks_dialog_babi_plus_README.html',1,'']]],
  ['task_3a_20dialog_20babi',['Task: Dialog bAbI',['../dd/d12/md_parlai_tasks_dialog_babi_README.html',1,'']]],
  ['task_3a_20dialogue_5fqe',['Task: Dialogue_QE',['../d2/d2b/md_parlai_tasks_dialogue_qe_README.html',1,'']]],
  ['task_3a_20empathetic_20dialogues',['Task: Empathetic Dialogues',['../d3/dde/md_parlai_tasks_empathetic_dialogues_README.html',1,'']]],
  ['task_3a_20flickr30k',['Task: Flickr30k',['../d4/d50/md_parlai_tasks_flickr30k_README.html',1,'']]],
  ['task_3a_20fvqa',['Task: FVQA',['../dd/d8f/md_parlai_tasks_fvqa_README.html',1,'']]],
  ['task_3a_20hotpotqa',['Task: HotpotQA',['../d3/dac/md_parlai_tasks_hotpotqa_README.html',1,'']]],
  ['task_3a_20image_5fchat',['Task: Image_Chat',['../df/d48/md_parlai_tasks_image_chat_README.html',1,'']]],
  ['task_3a_20insuranceqa',['Task: InsuranceQA',['../dd/d97/md_parlai_tasks_insuranceqa_README.html',1,'']]],
  ['task_3a_20integration_20tests',['Task: Integration Tests',['../d4/da6/md_parlai_tasks_integration_tests_README.html',1,'']]],
  ['task_3a_20interactive',['Task: Interactive',['../db/db8/md_parlai_tasks_interactive_README.html',1,'']]],
  ['task_3a_20iwslt14',['Task: IWSLT14',['../d3/d08/md_parlai_tasks_iwslt14_README.html',1,'']]],
  ['task_3a_20light_2ddialogue',['Task: LIGHT-Dialogue',['../d5/d76/md_parlai_tasks_light_dialog_README.html',1,'']]],
  ['task_3a_20mctest',['Task: MCTest',['../d3/dbb/md_parlai_tasks_mctest_README.html',1,'']]],
  ['task_3a_20mnist_5fqa',['Task: MNIST_QA',['../d3/d31/md_parlai_tasks_mnist_qa_README.html',1,'']]],
  ['task_3a_20movie_20dialog_20qa',['Task: Movie Dialog QA',['../d5/d66/md_parlai_tasks_moviedialog_README.html',1,'']]],
  ['task_3a_20ms_5fmarco',['Task: MS_MARCO',['../d6/d78/md_parlai_tasks_ms_marco_README.html',1,'']]],
  ['task_3a_20mturk_20wikimovies',['Task: MTurk WikiMovies',['../da/d82/md_parlai_tasks_mturkwikimovies_README.html',1,'']]],
  ['task_3a_20multinli',['Task: MultiNLI',['../d1/df7/md_parlai_tasks_multinli_README.html',1,'']]],
  ['task_3a_20mutualfriends',['Task: MutualFriends',['../d5/dba/md_parlai_tasks_mutualfriends_README.html',1,'']]],
  ['task_3a_20mwsc_20pronoun_20resolution',['Task: MWSC pronoun resolution',['../d3/d96/md_parlai_tasks_mwsc_README.html',1,'']]],
  ['task_3a_20narrativeqa',['Task: NarrativeQA',['../d3/d01/md_parlai_tasks_narrative_qa_README.html',1,'']]],
  ['task_3a_20nlvr',['Task: nlvr',['../dd/d6c/md_parlai_tasks_nlvr_README.html',1,'']]],
  ['task_3a_20one_20common',['Task: One Common',['../de/d5e/md_parlai_tasks_onecommon_README.html',1,'']]],
  ['task_3a_20open_20subtitles',['Task: Open Subtitles',['../dd/d3c/md_parlai_tasks_opensubtitles_README.html',1,'']]],
  ['task_3a_20persona_2dchat',['Task: Persona-Chat',['../df/dc0/md_parlai_tasks_personachat_README.html',1,'']]],
  ['task_3a_20personality_5fcaptions',['Task: Personality_Captions',['../d8/dc7/md_parlai_tasks_personality_captions_README.html',1,'']]],
  ['task_3a_20personalized_20dialog_20full_20set',['Task: Personalized Dialog Full Set',['../d5/d16/md_parlai_tasks_personalized_dialog_README.html',1,'']]],
  ['task_3a_20qa_20cnn',['Task: QA CNN',['../d6/ddf/md_parlai_tasks_qacnn_README.html',1,'']]],
  ['task_3a_20qa_20daily_20mail',['Task: QA Daily Mail',['../d9/d85/md_parlai_tasks_qadailymail_README.html',1,'']]],
  ['task_3a_20qangaroo',['Task: QAngaroo',['../d8/d81/md_parlai_tasks_qangaroo_README.html',1,'']]],
  ['task_3a_20qa_2dsrl_20semantic_20role_20labeling',['Task: QA-SRL Semantic Role Labeling',['../de/da9/md_parlai_tasks_qasrl_README.html',1,'']]],
  ['task_3a_20qa_2dzre_20relation_20extraction',['Task: QA-ZRE Relation Extraction',['../dc/d85/md_parlai_tasks_qazre_README.html',1,'']]],
  ['task_3a_20question_20answering_20in_20context',['Task: Question Answering in Context',['../db/d04/md_parlai_tasks_quac_README.html',1,'']]],
  ['task_3a_20scan',['Task: SCAN',['../d5/d5a/md_parlai_tasks_scan_README.html',1,'']]],
  ['task_3a_20self_2dfeeding_20chatbot',['Task: Self-Feeding Chatbot',['../d6/d5a/md_parlai_tasks_self_feeding_README.html',1,'']]],
  ['task_3a_20dialog_20babi',['Task: Dialog bAbI',['../da/d21/md_parlai_tasks_shadock_README.html',1,'']]],
  ['task_3a_20simple_20questions',['Task: Simple Questions',['../d0/dbb/md_parlai_tasks_simplequestions_README.html',1,'']]],
  ['task_3a_20the_20stanford_20natural_20language_20inference_20_28snli_29_20corpus',['Task: The Stanford Natural Language Inference (SNLI) Corpus',['../df/d61/md_parlai_tasks_snli_README.html',1,'']]],
  ['task_3a_20squad2',['Task: SQuAD2',['../d8/d86/md_parlai_tasks_squad2_README.html',1,'']]],
  ['task_3a_20squad',['Task: SQuAD',['../da/d86/md_parlai_tasks_squad_README.html',1,'']]],
  ['task_3a_20sst_20sentiment_20analysis',['Task: SST Sentiment Analysis',['../d1/d3c/md_parlai_tasks_sst_README.html',1,'']]],
  ['task_3a_20talk_20the_20walk',['Task: Talk the Walk',['../d5/da5/md_parlai_tasks_talkthewalk_README.html',1,'']]],
  ['task_3a_20task_20n_27_20talk',['Task: Task N&apos; Talk',['../d1/d17/md_parlai_tasks_taskntalk_README.html',1,'']]],
  ['task_3a_20triviaqa',['Task: TriviaQA',['../da/ded/md_parlai_tasks_triviaqa_README.html',1,'']]],
  ['task_3a_20twitter',['Task: Twitter',['../d8/dd7/md_parlai_tasks_twitter_README.html',1,'']]],
  ['task_3a_20ubuntu',['Task: Ubuntu',['../d7/d98/md_parlai_tasks_ubuntu_README.html',1,'']]],
  ['task_3a_20visdial',['Task: VisDial',['../df/d50/md_parlai_tasks_visdial_README.html',1,'']]],
  ['task_3a_20vqav1',['Task: VQAv1',['../dc/df9/md_parlai_tasks_vqa_v1_README.html',1,'']]],
  ['task_3a_20vqav2',['Task: VQAv2',['../d4/d8b/md_parlai_tasks_vqa_v2_README.html',1,'']]],
  ['task_3a_20web_20questions',['Task: Web Questions',['../de/db1/md_parlai_tasks_webquestions_README.html',1,'']]],
  ['task_3a_20wikimovies',['Task: WikiMovies',['../d4/d35/md_parlai_tasks_wikimovies_README.html',1,'']]],
  ['task_3a_20wikipedia',['Task: Wikipedia',['../d7/d00/md_parlai_tasks_wikipedia_README.html',1,'']]],
  ['task_3a_20wikiqa',['Task: WikiQA',['../d2/d02/md_parlai_tasks_wikiqa_README.html',1,'']]],
  ['task_3a_20wikisql_20semantic_20parsing_20task',['Task: WikiSQL semantic parsing task',['../de/daf/md_parlai_tasks_wikisql_README.html',1,'']]],
  ['task_3a_20wizard_5fof_5fwikipedia',['Task: Wizard_of_Wikipedia',['../dd/d62/md_parlai_tasks_wizard_of_wikipedia_README.html',1,'']]],
  ['task_3a_20wmt',['Task: WMT',['../dc/d0f/md_parlai_tasks_wmt_README.html',1,'']]],
  ['task_3a_20woz_20restuarant_20reservation_20_28goal_2doriented_20dialogue_29',['Task: WOZ restuarant reservation (Goal-Oriented Dialogue)',['../df/d7d/md_parlai_tasks_woz_README.html',1,'']]],
  ['the_20dialogue_20dodecathlon',['The Dialogue Dodecathlon',['../da/dc3/md_projects_dodecadialogue_README.html',1,'']]]
];
